[project]
name = "football-goal-detector"
version = "0.1.0"
description = "A scoreboard OCR system to detect football goal events from match videos"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "opencv-python-headless>=4.8.0",
    "numpy>=1.24.0",
    "pytesseract>=0.3.10",
    "matplotlib>=3.7.0",
    "tqdm>=4.65.0",
    "torch",
    "torchvision",
    "paddlepaddle",
    "paddleocr==3.7.0",
    "scenedetect>=0.7",
    "librosa>=0.11.0",
    "easyocr>=1.7.2",
    "opencv-python>=4.13.0.92",
    "pillow>=12.2.0",
    "python-dotenv>=1.2.2",
    "confluent-kafka>=2.3.0",
    "cryptography>=41.0.0",
    "pymysql>=1.2.0",
    "av>=18.0.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu121"
